version: '2'
services:
  mfsmaster:
    # image: moosefs/master
    build: ./moosefs-master
    container_name: "mfsmaster"
    networks:
      moosefsnet:
        ipv4_address: "172.20.0.2"
    ports:
      - "9425:9425"
  mfschunkserverclient1:
    # image: moosefs/chunkserver-client
    build: ./moosefs-chunkserver-client
    container_name: "mfschunkserverclient1"
    environment:
      - LABELS=M
      - SIZE=10
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    stdin_open: true
    tty: true
    links:
      - mfsmaster
    networks:
      moosefsnet:
        ipv4_address: "172.20.0.11"
    volumes:
            - ./data/cs1_hdd0:/mnt/hdd0
    depends_on:
      - mfsmaster
  mfschunkserverclient2:
    # image: moosefs/chunkserver-client
    build: ./moosefs-chunkserver-client
    container_name: "mfschunkserverclient2"
    environment:
      - LABELS=MB
      - SIZE=10
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    stdin_open: true
    tty: true
    links:
      - mfsmaster
    networks:
      moosefsnet:
        ipv4_address: "172.20.0.12"
    volumes:
            - ./data/cs2_hdd0:/mnt/hdd0
    depends_on:
      - mfsmaster
  mfschunkserverclient3:
    # image: moosefs/chunkserver-client
    build: ./moosefs-chunkserver-client
    container_name: "mfschunkserverclient3"
    environment:
      - LABELS=MB
      - SIZE=10
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    stdin_open: true
    tty: true
    links:
      - mfsmaster
    networks:
      moosefsnet:
        ipv4_address: "172.20.0.13"
    volumes:
            - ./data/cs3_hdd0:/mnt/hdd0
    depends_on:
      - mfsmaster
  mfschunkserverclient4:
    # image: moosefs/chunkserver-client
    build: ./moosefs-chunkserver-client
    container_name: "mfschunkserverclient4"
    environment:
      - LABELS=B
      - SIZE=10
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    stdin_open: true
    tty: true
    links:
      - mfsmaster
    networks:
      moosefsnet:
        ipv4_address: "172.20.0.14"
    volumes:
            - ./data/cs4_hdd0:/mnt/hdd0
    depends_on:
      - mfsmaster
networks:
  moosefsnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1
