version: '2'
services:
  mfsmaster:
    image: moosefs/master  #use GitHub version
    # build: ./moosefs-master  #use local version
    container_name: "mfsmaster"
    networks:
      moosefsnet:
        ipv4_address: "172.20.0.2"
    ports:
      - "9425:9425"
  mfsclient:
    image: moosefs/client  #use GitHub version
    # build: ./moosefs-client  #use local version
    container_name: "mfsclient"
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    stdin_open: true
    tty: true
    links:
      - mfsmaster
    networks:
      moosefsnet:
        ipv4_address: "172.20.0.5"
    depends_on:
      - mfsmaster
  mfschunkserver1:
    image: moosefs/chunkserver  #use GitHub version
    # build: ./moosefs-chunkserver  #use local version
    container_name: "mfschunkserver1"
    environment:
      - LABELS=M
      - SIZE=10
    links:
      - mfsmaster
    networks:
      moosefsnet:
        ipv4_address: "172.20.0.11"
    volumes:
            - ./data/cs1_hdd0:/mnt/hdd0
    depends_on:
      - mfsmaster
  mfschunkserver2:
    image: moosefs/chunkserver  #use GitHub version
    # build: ./moosefs-chunkserver  #use local version
    container_name: "mfschunkserver2"
    environment:
      - LABELS=MB
      - SIZE=10
    links:
      - mfsmaster
    networks:
      moosefsnet:
        ipv4_address: "172.20.0.12"
    volumes:
            - ./data/cs2_hdd0:/mnt/hdd0
    depends_on:
      - mfsmaster
  mfschunkserver3:
    image: moosefs/chunkserver  #use GitHub version
    # build: ./moosefs-chunkserver  #use local version
    container_name: "mfschunkserver3"
    environment:
      - LABELS=MB
      - SIZE=10
    links:
      - mfsmaster
    networks:
      moosefsnet:
        ipv4_address: "172.20.0.13"
    volumes:
            - ./data/cs3_hdd0:/mnt/hdd0
    depends_on:
      - mfsmaster
  mfschunkserver4:
    image: moosefs/chunkserver  #use GitHub version
    # build: ./moosefs-chunkserver  #use local version
    container_name: "mfschunkserver4"
    environment:
      - LABELS=B
      - SIZE=10
    links:
      - mfsmaster
    networks:
      moosefsnet:
        ipv4_address: "172.20.0.14"
    volumes:
            - ./data/cs4_hdd0:/mnt/hdd0
    depends_on:
      - mfsmaster
networks:
  moosefsnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1
